package org.drools.workshop;
import org.drools.workshop.model.*;


rule "Max Room Temp"
    when
        $m: SensorM(movimiento == true)
        $ac: ActuadorC($m.ubicacionE==ubicacionE && $m.ubicacionC==ubicacionC)
        $r: Cuarto($ac.ubicacionE==ubicacionE && $ac.ubicacionC==ubicacionC && $ac.temperatura>maxtemperatura )
    then
        $ac.setTemperatura($r.getMaxTemperatura());
    end

rule "Min Room Temp"

    when
        $m: SensorM(movimiento == true)
        $ac: ActuadorC($m.ubicacionE==ubicacionE && $m.ubicacionC==ubicacionC)
        $r: Cuarto($ac.ubicacionE==ubicacionE && $ac.ubicacionC==ubicacionC && $ac.temperatura < mintemperatura )
    then
         $ac.setTemperatura($r.getMinTemperatura());
    end

rule "No Movement"
    when
        $m: SensorM(movimiento == false)
        $r: Cuarto($m.ubicacionE==ubicacionE && $m.ubicacionC==ubicacionC)
        $ac: ActuadorC($m.ubicacionE==ubicacionE && $m.ubicacionC==ubicacionC)
        $af: ActuadorF($m.ubicacionE==ubicacionE && $m.ubicacionC==ubicacionC)
        $aa: ActuadorA($m.ubicacionE==ubicacionE && $m.ubicacionC==ubicacionC)

    then
        $ac.setConectado(false);
        $af.setConectado(false);
        $aa.setConectado(false);
end

rule "Consumo de Energia"
    when
        $m: SensorM(movimiento == true)
        $r: Cuarto($m.ubicacionE==ubicacionE && $m.ubicacionC==ubicacionC)
        $ac: ActuadorC($m.ubicacionE==ubicacionE && $m.ubicacionC==ubicacionC)
        $af: ActuadorF($m.ubicacionE==ubicacionE && $m.ubicacionC==ubicacionC)
        $aa: ActuadorA($m.ubicacionE==ubicacionE && $m.ubicacionC==ubicacionC)
         eval(($ac.getConsumoEnergia()+$af.getConsumoEnergia()+$aa.getConsumoEnergia()) > $r.getMaxConsumoEnergia())
    then
        $aa.setConsumoEnergia($r.getMinConsumoEnergia());
        $aa.setConsumoEnergia($r.getMinConsumoEnergia());
        $aa.setConsumoEnergia($r.getMinConsumoEnergia());
end

rule "Max Vel"
    when
        $m: SensorM(movimiento == true)
        $aa: ActuadorA($m.ubicacionE==ubicacionE && $m.ubicacionC==ubicacionC)
        $r: Cuarto($aa.ubicacionE==ubicacionE && $aa.ubicacionC==ubicacionC && maxVelocidad <= $aa.velocidad)
    then
        $aa.setVelocidad($r.getMaxVelocidad());
    end

rule "Min Vel"
    when
        $m: SensorM(movimiento == true)
        $aa: ActuadorA($m.ubicacionE==ubicacionE && $m.ubicacionC==ubicacionC)
        $r: Cuarto($aa.ubicacionE==ubicacionE && $aa.ubicacionC==ubicacionC && minVelocidad >= $aa.velocidad)
    then
        $aa.setVelocidad($r.getMinVelocidad());
    end

